name: Lint
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      PUBLIC_API_URL: https://dlool-backend.onrender.com
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'

      - run: pnpm install
        name: Install dependencies
      - run: pnpm lint
        name: Lint
